version: '3'
services:
  order-expert-service-app:
    build: ./spring-boot-2-order-expert-service/target
    networks:
     - backend
    depends_on:
     - db
    environment:
      - SPRING_REDIS_HOST=db

  order-expert-booking-service-app:
    build: ./spring-boot-2-order-expert-booking-service/target
    networks:
     - backend
    depends_on:
     - db
    environment:
      - SPRING_REDIS_HOST=db

  db:
    hostname: redis
    image: "redis:alpine"
    ports:
     - "6379:6379"
    networks:
     - backend

  nginx-lb:
    container_name: nginx-lb
    image: nginx:1.14
    restart: always
    ports:
     - 80:80
     - 443:443
    volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
     - backend
    depends_on:
     - order-expert-service-app
     - order-expert-booking-service-app

networks:
  backend:
    driver: bridge